package cc.wudoumi.article.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ARTICLE_TYPE.
 */
public class ArticleType {

    private Long _id;
    private Integer id;
    private String name;
    private Integer parentId;
    private String color;

    public ArticleType() {
    }

    public ArticleType(Long _id) {
        this._id = _id;
    }

    public ArticleType(Long _id, Integer id, String name, Integer parentId, String color) {
        this._id = _id;
        this.id = id;
        this.name = name;
        this.parentId = parentId;
        this.color = color;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getParentId() {
        return parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

}
